project:
  type: website
  output-dir: ../docs
  render:
    - "**/*.qmd"

website:
  title: Isfar Baset Portfolio
  navbar:
    background: primary
    search: true
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/isfarbaset/
        text: "LinkedIn"
      - icon: github
        href: https://github.com/isfarbaset
        text: "GitHub"
  sidebar:
    style: "floating"
    contents:
      - icon: envelope
        text: "Email"
        href: "mailto:isfar.baset@gmail.com"
      - text: " "  # Empty spacer item
      - icon: file-earmark-text
        text: "Resume"
        href: "Isfar Baset Resume.pdf"


format:
  html:
    theme: cosmo
    css: style.css
    toc: true
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">