project:
  type: website
  output-dir: ../docs
  render:
    - "**/*.qmd"

website:
  title: Isfar Baset
  site-url: "/"
  navbar:
    background: primary
    search: true
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/isfarbaset/
      - icon: github
        href: https://github.com/isfarbaset


format:
  html:
    theme: cosmo
    css: style.css
    toc: true
    html-math-method: mathjax
    include-in-header:
      text: |
        <meta name="viewport" content="width=device-width, initial-scale=1.0">